name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v3.11.0
        with:
          java-version: 11.0.19+7
          distribution: adopt
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Prepare database for integration tests
        run: | 
          sudo /etc/init.d/mysql start
          mysql -uroot -proot < sql/HotelManagementDB.sql
          mvn --batch-mode --update-snapshots compile datanucleus:enhance datanucleus:schema-delete -DskipTests -pl Server
      - name: Run server
        run: | 
          mvn --batch-mode --update-snapshots datanucleus:enhance exec:java -pl Server &

      - name: Run JUnits
        run: | 
          sleep 7 
          mvn --batch-mode --update-snapshots test

      - name: Build client
        run: |
          mvn --batch-mode --update-snapshots install -pl Client -DskipTests
          echo ${{ steps.version.outputs.TAG_NAME }}

      - name: Retrieve version
        run: echo "::set-output name=TAG_NAME::$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)"
        id: version

      - uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: ${{ steps.version.outputs.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./Client/target/Client-${{ steps.version.outputs.TAG_NAME }}-jar-with-dependencies.jar
          asset_name: Client.jar
          tag: ${{ steps.version.outputs.TAG_NAME }}
          release_name: ${{ steps.version.outputs.TAG_NAME }}
          overwrite: true
        
      - name: Generate Doxigen documentation
        uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: docs
          config_file: Doxyfile
        #uses: mattnotmitt/doxygen-action@v1.9.5
        #with:
            #working-directory: 'submodule/'
            #doxyfile-path: 'docs/Doxyfile'
            #enable-latex: true
